### ISSUE TITLE
Use username instead of email to login

### ISSUE THREAD

**Issue by scramatte** [Muetze42/nova-assets-changer#2]
Hello,

I would like to use username instead of email on login page.
Can you give me an hand ?

Regards

**Comment by mateusgalasso** [comment]
Just remove type="email" and put type="text"

```
<input
    v-model="form.email"
    class="form-control form-input form-input-bordered w-full"
    :class="{ 'form-input-border-error': form.errors.has('email') }"
    id="email"
    type="text"
    name="email"
    autofocus=""
    required
  />
```

**Comment by Muetze42** [comment]
But then the name should also be unique.

I have also added a method to register pages in Nova. 
I just have to write a readme for it....
There the login page is also edited.

https://www.youtube.com/watch?v=kVoYtmVgmOs

**Comment by chrillep** [comment]
ref: 

- https://github.com/laravel/nova-issues/discussions/3954
- https://github.com/laravel/nova-issues/issues/3952

**Comment by Muetze42** [comment]
https://github.com/Muetze42/nova-assets-changer/blob/main/docs/register-page.md

**Comment by Muetze42** [comment]
A way to realize without changing Nova assets:

https://github.com/Muetze42/laravel-nova-example-projects/tree/feature/custom-login

**Comment by BobbyBorisov** [comment]
@Muetze42 I am trying to adapt the custom login to my needs from the custom login from the example project that you provided but somehow it does not work without specifying the root like this `Inertia::setRootView('app');` just before returning the view. It looks like its trying to load the Nova one because I can see [NOVA] Initiating Nova countdown... in the console. Any idea why is that? I downloaded your example project and it works.

I have gone through your commits that you suggest and done everything. I even have views/app.blade.php root file that inertia should choose it by default but without explicitly telling it it does not work
